### get users
GET localhost:8080/api/user

### create user

POST localhost:8080/api/user
Content-Type: application/json

{
  "password": "test123",
  "email": "ahmed@blog.com"
}

###delete user
DELETE localhost:8080/api/user/1

### get posts
GET localhost:8080/api/post

### create post
POST http://localhost:8080/api/post/ahmed
Content-Type: application/json

{
  "title": "test post",
  "description": "test description"
}

### add comment
POST localhost:8080/api/post/action/comment/1/ahmed
Content-Type: application/json

{
  "content": "test post"
}

### post upvote
POST localhost:8080/api/post/action/1/upvote


