spring:
  datasource:
    url: jdbc:mysql://localhost:3306:BlogDatabase
    username: root
    password: P@ssw0rd1337
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql